### ISSUE TITLE
Example for pickone, weighted and other method with array ?

### ISSUE THREAD

**Issue by Gounlaf** [tanshiqi/Paw-ChanceDynamicValue#2]
Hi,

I succeed to use method with object as parameter, but not ones with arrays, like pickone or weighted. I got javascript errors (see attachments).

Is it possible to have an example ?

Thanks,

Regards

![capture d ecran 2016-05-14 a 15 40 29](https://cloud.githubusercontent.com/assets/236413/15268791/8a49d042-19ea-11e6-9f3d-af97fb0e3332.png)
![capture d ecran 2016-05-14 a 15 39 57](https://cloud.githubusercontent.com/assets/236413/15268792/8a4de63c-19ea-11e6-82e7-314a2dce2987.png)

**Comment by tanshiqi** [comment]
Update. Please try again.

**Comment by Gounlaf** [comment]
Hi,

Thanks for update. I have copy/past [ChanceDynamicValue.js](https://raw.githubusercontent.com/tanshiqi/Paw-ChanceDynamicValue/master/ChanceDynamicValue.js) directly in paw "Extensions" / com.atan.PawExtensions.ChanceDynamicValue.
I also clicked on "Reload installed extensions".

But it's still not working.

Errors are identicals.

**Comment by Gounlaf** [comment]
My bad, it works ! Thanks
